trigger:
  branches:
    include:
    - '*'

variables:
  buildConfiguration: 'Release'
  webRepository: 'dumindukm/rmssln'
  tag: '$(Build.BuildId)'
  WebAppName: 'rmsweb-cnt'

stages:
- stage: 'Build'
  displayName: 'Build the Web App'
  jobs:
  - job: 'Build'
    displayName: 'Build Job'
    pool:
      vmImage: ubuntu-latest

    steps:
    # - task: Docker@2
    #   displayName: 'Build and push the image to container registry'
    #   inputs:
    #     command: buildAndPush
    #     buildContext: $(Build.Repository.LocalPath)/src/rms-web/Rms.Pos/Rms.Web
    #     repository: $(webRepository)
    #     dockerfile: '$(Build.SourcesDirectory)/src/rms-web/Rms.Pos/Rms.Web/Dockerfile'
    #     containerRegistry: '$(dockerhub-servicecnt)'
    #     tags: |
    #       $(tag)
    - template: docker-build-push.yml
      parameters:
        dockerhub-servicecnt: '$(dockerhub-servicecnt)'
        tag: $(tag)
        project-path: 'src/rms-web/Rms.Pos/Rms.Web'
        docker-repo: $(webRepository)

- stage: 'Deploy'
  displayName: 'Deploy the container'
  dependsOn: Build
  jobs:
  - job: 'Deploy'
    displayName: 'Deploy job'
    pool:
      vmImage: 'ubuntu-latest'
    # variables:
    # - group: Release-stage
    steps:
    - task: AzureWebAppContainer@1
      inputs:
       appName: $(WebAppName)
       azureSubscription: 'azsub-servicecnt'
       imageName: $(webRepository):$(tag)